# Generated by Django 5.2.4 on 2025-08-02 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_product_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('EL', 'Mobile Phones'), ('FI', 'Fashion'), ('HK', 'Home & Kitchen'), ('LP', 'Laptops'), ('CM', 'Cameras'), ('OT', 'Others')], default='OT', max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
