# Generated by Django 5.2.4 on 2025-08-05 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_product_is_available_product_model_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('EL', 'Mobile Phones'), ('HE', 'headphones and Earbuds'), ('HK', 'Home & Kitchen'), ('LP', 'Laptops'), ('CM', 'Cameras'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
