# Generated by Django 5.2.5 on 2025-08-10 19:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0005_alter_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='model_number',
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('EL', 'Mobile Phones'), ('HE', 'Headphones and Earbuds'), ('HK', 'Home & Kitchen'), ('LP', 'Laptops'), ('CM', 'Cameras'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
