# Generated by Django 5.2.5 on 2025-08-10 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_remove_product_model_number_product_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
    ]
