# Generated by Django 5.2.5 on 2025-08-11 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0008_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('EL', 'Electronics'), ('FS', 'Fashion'), ('HK', 'Home & Kitchen'), ('ST', 'Sports'), ('OT', 'Others')], default='OT', max_length=2),
        ),
    ]
