# Generated by Django 5.2.5 on 2025-08-12 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0009_alter_product_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
    ]
